# Generated by Django 3.1.7 on 2021-03-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplewallet',
            old_name='username',
            new_name='user_id',
        ),
    ]
