# Generated by Django 3.1.7 on 2021-04-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swallet', '0003_auto_20210401_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet_name',
            new_name='wallet_id',
        ),
    ]
